#export CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk
#export CFLAGS="${CFLAGS} -i sysroot ${CONDA_BUILD_SYSROOT}"
$PYTHON setup.py install
#export CMAKE_LIBRARY_PATH="$SYS_PREFIX:$CMAKE_LIBRARY_PATH"
#export CMAKE_INCLUDE_PATH="$SYS_PREFIX:$CMAKE_INCLUDE_PATH"
#export BOOST_ROOT=$SYS_PREFIX
#export CPLUS_INCLUDE_PATH=$SYS_PREFIX/include
#export LD_LIBRARY_PATH=$SYS_PREFIX/lib:${LD_LIBRARY_PATH}
echo $SYS_PREFIX
rm -rf build
mkdir -p build 
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DBoost_NO_BOOST_CMAKE=ON #-DBoost_INCLUDE_DIRS=${CONDA_PREFIX}/include -DBoost_LIBRARIES=${CONDA_PREFIX}/lib
make 
make install
