package:
  name: smcsmc
  version: 1.0.2b

source:
  path: ..

build:
  number: 2
  entry_points:
    - smc2=smcsmc.cli:smcsmc_main

requirements:
  build:
    - {{ compiler('cxx') }}
    - gperftools 
    - python {{ python }}
    - cmake
    - boost
    - zlib
    - tqdm

  host:
    - python {{ python }}
    - numpy
    - pandas
    - tqdm
    - msprime

  run:
    - gperftools
    - numpy
    - pandas
    - boost
    - python
    - zlib 
    - matplotlib
    - tqdm
    - msprime
    - tskit

test:
  imports:
    - smcsmc
  commands:
    - smc2 -h
    - smcsmc -h
    - scrm -h

about:
  home: https://github.com/luntergroup/smcsmc
  doc_url: https://smcsmc.readthedocs.io
  summary: 'A particle filter for demographic inference.'

extra:
  recipe-maintainers:
    - Chris1221
