package:
  name: smcsmc
  version: 1.0

source:
  path: ..

build:
  number: 0
  entry_points:
    - smc2=smcsmc.cli:smcsmc_main

requirements:
  build:
    - {{ compiler('cxx') }} 
    - gperftools 
    - cmake
    - boost
    - zlib

  run:
    - gperftools
    - boost 
    - python
    - boost
    - zlib
