package:
  name: smcsmc
  version: 0.1

source:
  path: ..

requirements:
  build:
    - {{ compiler('cxx') }} 
    - gperftools 
    - cmake
    - boost
    - zlib

  host:
    - gperftools
    - boost 
    - python
    - boost
    - zlib
