package:
  name: smcsmc
  version: 1.0.1

source:
  path: ..

build:
  number: 0
  entry_points:
    - smc2=smcsmc.cli:smcsmc_main

requirements:
  build:
    - {{ compiler('cxx') }} 
    - gperftools 
    - cmake
    - boost
    - zlib
    - msprime

  host:
    - python
    - msprime
    - numpy
    - pandas

  run:
    - gperftools
    - numpy
    - pandas
    - msprime
    - boost 
    - python
    - boost
    - zlib 
    - matplotlib

test:
  imports:
    - smcsmc

about:
  home: https://github.com/luntergroup/smcsmc
  doc_url: https://smcsmc.readthedocs.io
  summary: 'A particle filter for demographic inference.'
