language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind r-base-core; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm cppunit graphviz valgrind && brew link --force llvm; fi
before_script:
  - ./bootstrap

script:
  - make 
  - cd tests; ./test_epoch_lag.sh
  - ./test_binary_sample_size.sh
