language: cpp
os:
  - osx
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - .travis/before_install.sh
before_script:
  - ./bootstrap

script:
  - make; sudo make install
  - make check
  - cd tests;
  - ./test_binary_sample_size.sh
  - ./test_binaries1_10.sh
  #- ./check_smcsmcSCRM_vs_scrm.sh;
  #- if [ $TRAVIS_OS_NAME == osx ]; then sed -e "s/end=20/end=3/g" check_smcsmcRECOMBOFF.sh ; > check_smcsmcRECOMBOFF_osx.sh ; chmod a+x check_smcsmcRECOMBOFF_osx.sh; mv check_smcsmcRECOMBOFF_osx.sh ./check_smcsmcRECOMBOFF.sh; fi
  #- ./check_smcsmcRECOMBOFF.sh;
  - cd ..
  #- cd tests; ./test_epoch_lag.sh; cd ..
  #- cd tests; ./test_binary_sample_size.sh; cd ..
