language: cpp
os:
  - osx
  - linux

compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind r-base-core; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm cppunit graphviz valgrind && brew link --force llvm; fi
before_script:
  - ./bootstrap

script:
  - make; sudo make install
  - make check
  - cd tests; 
  - ./check_smcsmcSCRM_vs_scrm.sh; 
  - if [ $TRAVIS_OS_NAME == osx ]; then sed -e "s/end=20/end=3/g" check_smcsmcRECOMBOFF.sh ; > check_smcsmcRECOMBOFF_osx.sh ; chmod a+x check_smcsmcRECOMBOFF_osx.sh; mv check_smcsmcRECOMBOFF_osx.sh ./check_smcsmcRECOMBOFF.sh; fi
  - ./check_smcsmcRECOMBOFF.sh;
  - cd ..
  #- cd tests; ./test_epoch_lag.sh; cd ..
  #- cd tests; ./test_binary_sample_size.sh; cd ..
