version: 2.1

orbs:
  python: circleci/python@0.2.1

branches:
  only:
    - master

jobs:
  build-smcsmc:
    executor: python/default
    steps:
      - checkout
      - run:
          command: sudo apt-get install -y gcc cmake libboost-all-dev google-perftools build-essential zlib1g-dev
          name: SMCSMC dependencies
      - run:
          command: set -ex; mkdir build; cd build; cmake ..; make; ln -s $PWD/smcsmc /usr/local/bin/smcsmc
          name: Build SMCSMC
  build-and-test-python:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install setuptools_scm; pip install numpy; pip install -r requirements.txt
          name: Install dependencies
      - run:
          command: pip install .
          name: Install
      - run:
          command: pytest test/ --ignore test/old
          name: Test

workflows:
  main:
    jobs:
      - build-smcsmc
      - build-and-test-python
